ALTER TABLE invoices
  ADD COLUMN IF NOT EXISTS buyer_tax_no VARCHAR(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS buyer_address_phone VARCHAR(256) DEFAULT '',
  ADD COLUMN IF NOT EXISTS buyer_bank_account VARCHAR(256) DEFAULT '',
  ADD COLUMN IF NOT EXISTS seller_tax_no VARCHAR(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS seller_address_phone VARCHAR(256) DEFAULT '',
  ADD COLUMN IF NOT EXISTS seller_bank_account VARCHAR(256) DEFAULT '',
  ADD COLUMN IF NOT EXISTS item_name VARCHAR(512) DEFAULT '',
  ADD COLUMN IF NOT EXISTS item_spec VARCHAR(128) DEFAULT '',
  ADD COLUMN IF NOT EXISTS item_unit VARCHAR(32) DEFAULT '',
  ADD COLUMN IF NOT EXISTS item_quantity NUMERIC(18,6) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS item_unit_price NUMERIC(18,6) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_amount_cn VARCHAR(128) DEFAULT '';
